"""
seed_and_test.py
────────────────
1. Loads 100 synthetic attendees into the search service via POST /attendees/bulk
2. Runs 12 test queries and prints ranked results with scores

Usage:
    python scripts/seed_and_test.py                   # uses localhost:8001
    python scripts/seed_and_test.py --url http://x.x.x.x:8001
    python scripts/seed_and_test.py --test-only       # skip seeding, just search
"""

import sys
import json
import argparse
import httpx

BASE_URL = "http://localhost:8001"

# ── 100 synthetic attendees ────────────────────────────────────────────────────
ATTENDEES = [
    # ── ML / AI Engineers (1–18) ──────────────────────────────────────────────
    {
        "id": "usr_001",
        "full_name": "Arjun Mehta",
        "email": "arjun.mehta@deepvision.ai",
        "phone": "+91-9812345678",
        "organization": "DeepVision AI",
        "role": "Senior ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "I build large-scale computer vision pipelines for autonomous inspection drones. Specialise in PyTorch, ONNX model optimisation, and edge deployment on NVIDIA Jetson. Previously led the vision team at a Series B robotics startup. Passionate about making ML models run efficiently on constrained hardware. Open to collaborations on industrial AI and embedded ML.",
        "linkedin_url": "https://linkedin.com/in/arjunmehta-ml",
    },
    {
        "id": "usr_002",
        "full_name": "Priya Nair",
        "email": "priya.nair@llmforge.io",
        "phone": "+91-9823456789",
        "organization": "LLMForge",
        "role": "NLP Research Engineer",
        "experience_level": "mid",
        "detailed_profile": "Working on instruction fine-tuning and RLHF for domain-specific LLMs. My focus is on reducing hallucinations in medical and legal text generation. Built RAG pipelines using LangChain and Weaviate. Strong background in transformers, attention mechanisms, and evaluation benchmarks. Looking to connect with researchers working on grounded generation and factual consistency.",
        "linkedin_url": "https://linkedin.com/in/priyanair-nlp",
    },
    {
        "id": "usr_003",
        "full_name": "Rohan Desai",
        "email": "rohan@scalable-ml.com",
        "phone": "+91-9834567890",
        "organization": "Scalable ML",
        "role": "MLOps Engineer",
        "experience_level": "senior",
        "detailed_profile": "I design ML infrastructure at scale — Kubernetes-based training clusters, Kubeflow pipelines, real-time feature stores with Feast. Helped three startups move from notebook chaos to production-grade ML platforms. Obsessed with model monitoring, data drift detection, and reproducible experiments. Currently exploring eBPF for ML workload profiling.",
        "linkedin_url": "https://linkedin.com/in/rohandesai-mlops",
    },
    {
        "id": "usr_004",
        "full_name": "Sneha Kulkarni",
        "email": "sneha.k@airesearch.in",
        "phone": "+91-9845678901",
        "organization": "IIT Bombay AI Lab",
        "role": "PhD Researcher",
        "experience_level": "mid",
        "detailed_profile": "Third-year PhD student at IIT Bombay, researching efficient transformer architectures. Published on structured pruning and knowledge distillation at NeurIPS and ICML. Particularly interested in making LLMs deployable in low-bandwidth rural India settings. Side project: multilingual speech-to-text for 12 Indian languages. Looking for industry research internships.",
        "linkedin_url": "https://linkedin.com/in/snehakulkarni-phd",
    },
    {
        "id": "usr_005",
        "full_name": "Vikram Sharma",
        "email": "vikram@neuralsystems.dev",
        "phone": "+91-9856789012",
        "organization": "Neural Systems",
        "role": "Deep Learning Engineer",
        "experience_level": "senior",
        "detailed_profile": "Seven years building deep learning systems for recommendation and ranking at internet scale. Ex-Flipkart, ex-Juspay. Specialise in two-tower models, approximate nearest neighbour search, and online learning systems. Led migration of recommendation stack serving 50M users from TF1 to PyTorch. Mentoring junior engineers at my current company.",
        "linkedin_url": "https://linkedin.com/in/vikramsharma-dl",
    },
    {
        "id": "usr_006",
        "full_name": "Ananya Bose",
        "email": "ananya@genai-studio.com",
        "phone": "+91-9867890123",
        "organization": "GenAI Studio",
        "role": "AI Product Engineer",
        "experience_level": "mid",
        "detailed_profile": "I sit at the intersection of product and engineering — taking LLM capabilities and turning them into usable B2B products. Built an AI contract review tool used by 40+ law firms. Deeply familiar with prompt engineering, function calling, structured output, and latency optimisation. Previously in product management before moving to engineering. Interested in AI tooling and developer experience.",
        "linkedin_url": "https://linkedin.com/in/ananyabose-ai",
    },
    {
        "id": "usr_007",
        "full_name": "Karan Joshi",
        "email": "karan.joshi@ml-platform.io",
        "phone": "+91-9878901234",
        "organization": "ML Platform Co",
        "role": "Staff ML Engineer",
        "experience_level": "expert",
        "detailed_profile": "10+ years in ML engineering. Currently building the internal ML platform at a unicorn fintech. Expert in distributed training (FSDP, DeepSpeed), experiment tracking, and model registries. Wrote a popular open-source Python library for ML pipeline orchestration with 3k GitHub stars. Speaker at PyCon India and PyData. Mentoring ML engineers across India through an online community.",
        "linkedin_url": "https://linkedin.com/in/karanjoshi-mlplatform",
    },
    {
        "id": "usr_008",
        "full_name": "Meera Pillai",
        "email": "meera.pillai@aiops.tech",
        "phone": "+91-9889012345",
        "organization": "AIOps Technologies",
        "role": "AI Infrastructure Engineer",
        "experience_level": "senior",
        "detailed_profile": "Specialise in GPU cluster management, CUDA kernel optimisation, and LLM serving infrastructure. Benchmarked and deployed vLLM, TGI, and TensorRT-LLM for production workloads. Reduced inference cost by 60% at my current company through batching and quantisation strategies. Writing a guide on open-source LLM deployment. Happy to connect with anyone working on inference efficiency.",
        "linkedin_url": "https://linkedin.com/in/meerapillai-infra",
    },
    {
        "id": "usr_009",
        "full_name": "Siddharth Rao",
        "email": "sid@data-science-guild.com",
        "phone": "+91-9890123456",
        "organization": "Data Science Guild",
        "role": "Principal Data Scientist",
        "experience_level": "expert",
        "detailed_profile": "Building causal inference frameworks for policy evaluation at a public sector analytics firm. Background in econometrics, A/B testing, and uplift modelling. Previously at Google and Walmart Labs. Strong opinions on why correlation-based ML fails for decision-making. Teaching a course on causal ML at an online bootcamp. Interested in connecting with economists, policy researchers, and social scientists using ML.",
        "linkedin_url": "https://linkedin.com/in/siddharthrao-causal",
    },
    {
        "id": "usr_010",
        "full_name": "Nidhi Agarwal",
        "email": "nidhi.agarwal@reinforceai.in",
        "phone": "+91-9801234567",
        "organization": "ReinforceAI",
        "role": "Reinforcement Learning Engineer",
        "experience_level": "mid",
        "detailed_profile": "Working on RL for supply chain optimisation — routing, inventory, and demand forecasting. Implemented PPO and SAC algorithms from scratch. Familiar with Gymnasium, RLlib, and custom simulation environments. Previously did RL research for robotic manipulation at a university lab. Looking to collaborate with logistics and operations researchers who want to apply RL to real-world problems.",
        "linkedin_url": "https://linkedin.com/in/nidhiagarwal-rl",
    },
    {
        "id": "usr_011",
        "full_name": "Abhishek Tiwari",
        "email": "ab.tiwari@cv-labs.ai",
        "phone": "+91-9712345678",
        "organization": "CV Labs",
        "role": "Computer Vision Lead",
        "experience_level": "senior",
        "detailed_profile": "Leading computer vision R&D at a manufacturing AI company. Built defect detection systems deployed at 15 factories across Gujarat. Deep expertise in object detection (YOLO family), segmentation (SAM, Mask R-CNN), and 3D point cloud processing. Contributed to OpenCV and Detectron2. Interested in connecting with people applying vision AI to industrial and quality control settings.",
        "linkedin_url": "https://linkedin.com/in/abhishektiwari-cv",
    },
    {
        "id": "usr_012",
        "full_name": "Divya Menon",
        "email": "divya.menon@speechai.co",
        "phone": "+91-9723456789",
        "organization": "SpeechAI",
        "role": "Speech & Audio ML Engineer",
        "experience_level": "mid",
        "detailed_profile": "Building ASR and TTS systems for Indian languages. Fine-tuned Whisper for 8 Indian languages with industry-leading accuracy on noisy call centre audio. Also working on speaker diarisation and emotion detection from voice. Background in signal processing and linguistics. Open to collaboration on low-resource language AI, voice assistants, and audio-based accessibility tools.",
        "linkedin_url": "https://linkedin.com/in/divyamenon-speech",
    },
    {
        "id": "usr_013",
        "full_name": "Rahul Verma",
        "email": "rahul.v@graphml.dev",
        "phone": "+91-9734567890",
        "organization": "GraphML Research",
        "role": "Graph ML Researcher",
        "experience_level": "mid",
        "detailed_profile": "PhD dropout turned industry researcher working on graph neural networks for fraud detection and drug discovery. Familiar with PyG, DGL, and custom CUDA graph kernels. Published papers on heterogeneous graph transformers. Currently applying GNNs to transaction networks at a payments company. Looking to connect with people working on GNNs, knowledge graphs, and relational AI.",
        "linkedin_url": "https://linkedin.com/in/rahulverma-gnn",
    },
    {
        "id": "usr_014",
        "full_name": "Kavita Sharma",
        "email": "kavita.s@multimodal.ai",
        "phone": "+91-9745678901",
        "organization": "MultiModal AI",
        "role": "Multimodal AI Engineer",
        "experience_level": "senior",
        "detailed_profile": "Working on vision-language models — CLIP-style contrastive learning, image captioning, and visual question answering. Recent work on fine-tuning LLaVA for document understanding. Experienced with Hugging Face ecosystem, datasets, and model evaluation. Interested in AI for education — building tools that let students ask questions about diagrams and textbook images.",
        "linkedin_url": "https://linkedin.com/in/kavitasharma-multimodal",
    },
    {
        "id": "usr_015",
        "full_name": "Praveen Kumar",
        "email": "praveen.k@databricks-partner.com",
        "phone": "+91-9756789012",
        "organization": "DataStack Consulting",
        "role": "ML Platform Architect",
        "experience_level": "expert",
        "detailed_profile": "12 years building data and ML platforms. Certified Databricks architect, extensive experience with Delta Lake, MLflow, and Spark ML. Helped 20+ enterprises build end-to-end ML pipelines. Strong advocate for data mesh and federated ML governance. Recently exploring LLM fine-tuning workflows on Databricks. Happy to advise startups on ML infrastructure choices.",
        "linkedin_url": "https://linkedin.com/in/praveenkumar-mlarch",
    },
    {
        "id": "usr_016",
        "full_name": "Tanvi Patil",
        "email": "tanvi.patil@responsible-ai.org",
        "phone": "+91-9767890123",
        "organization": "Responsible AI Foundation",
        "role": "AI Ethics Researcher",
        "experience_level": "mid",
        "detailed_profile": "Researching bias, fairness, and accountability in AI systems. Led audits of credit scoring and hiring algorithms used in India. Background in social science and computer science. Published in FAccT and AIES. Working on a framework for AI impact assessment for Indian regulators. Interested in connecting with policymakers, civil society, and technologists working on trustworthy AI.",
        "linkedin_url": "https://linkedin.com/in/tanvipatil-aithics",
    },
    {
        "id": "usr_017",
        "full_name": "Aditya Singh",
        "email": "aditya@timeseries.ai",
        "phone": "+91-9778901234",
        "organization": "TimeSeriesAI",
        "role": "Forecasting ML Engineer",
        "experience_level": "mid",
        "detailed_profile": "Specialising in time series forecasting and anomaly detection for energy grids and industrial IoT. Built transformer-based forecasting models (PatchTST, Chronos) deployed for demand prediction at a power utility. Familiar with Prophet, NeuralProphet, and statistical baselines. Looking to connect with people in energy, manufacturing, and IoT who want to apply ML to sensor data.",
        "linkedin_url": "https://linkedin.com/in/adityasingh-timeseries",
    },
    {
        "id": "usr_018",
        "full_name": "Pooja Iyer",
        "email": "pooja.iyer@federated.ml",
        "phone": "+91-9789012345",
        "organization": "Federated ML Labs",
        "role": "Privacy-Preserving ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building federated learning and differential privacy systems for healthcare and finance. Implemented FL pipelines using Flower framework across 50 hospital nodes without sharing patient data. Familiar with secure aggregation, homomorphic encryption basics, and differential privacy (OpenDP). Interested in privacy-preserving AI, data sovereignty, and regulations like DPDP Act.",
        "linkedin_url": "https://linkedin.com/in/poojaiyer-privacyml",
    },

    # ── Healthcare AI (19–30) ──────────────────────────────────────────────────
    {
        "id": "usr_019",
        "full_name": "Dr. Anil Krishnan",
        "email": "anil.krishnan@aiims-collab.in",
        "phone": "+91-9890123456",
        "organization": "AIIMS Delhi",
        "role": "Radiologist & AI Researcher",
        "experience_level": "expert",
        "detailed_profile": "Radiologist with 15 years of clinical experience, now leading AI research at AIIMS Delhi. Developed deep learning models for chest X-ray and CT scan interpretation deployed in 8 government hospitals. Interested in AI tools that augment clinicians in resource-constrained settings. Collaborating with ML engineers to create robust, explainable diagnostic AI. Open to partnerships with AI labs and healthtech startups.",
        "linkedin_url": "https://linkedin.com/in/dranilkrishnan-radiology",
    },
    {
        "id": "usr_020",
        "full_name": "Shruti Bhatia",
        "email": "shruti.b@clinicalai.in",
        "phone": "+91-9801234567",
        "organization": "ClinicalAI",
        "role": "Clinical NLP Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building NLP systems to extract structured data from clinical notes, discharge summaries, and lab reports. Trained NER and relation extraction models on clinical text (SNOMED-CT, ICD-10 coding). Familiar with HL7 FHIR and healthcare data interoperability. Previously at a US-based EHR company. Passionate about using AI to reduce physician documentation burden.",
        "linkedin_url": "https://linkedin.com/in/shrutibhatia-clinicalnlp",
    },
    {
        "id": "usr_021",
        "full_name": "Dr. Meghna Roy",
        "email": "meghna.roy@genomicai.in",
        "phone": "+91-9812345679",
        "organization": "Genomic AI India",
        "role": "Computational Biologist",
        "experience_level": "expert",
        "detailed_profile": "Applying ML to genomics — variant calling, protein structure prediction, and drug target identification. Experience with AlphaFold, ESMFold, and graph neural networks for molecular property prediction. PhD in bioinformatics from IISc. Currently building tools for population-scale genomics in Indian cohorts. Interested in precision medicine, rare disease diagnostics, and AI drug discovery.",
        "linkedin_url": "https://linkedin.com/in/meghnaroy-genomics",
    },
    {
        "id": "usr_022",
        "full_name": "Suresh Nambiar",
        "email": "suresh@healthbot.io",
        "phone": "+91-9823456780",
        "organization": "HealthBot",
        "role": "Co-founder & CTO",
        "experience_level": "expert",
        "detailed_profile": "Co-founded HealthBot, a conversational AI platform for patient triage and symptom checking used by 200k patients monthly. Background in ML and healthcare operations. Built LLM-powered doctor-patient communication tools in 6 Indian languages. Seed funded, currently raising Series A. Looking to connect with health system leaders, investors in digital health, and clinical AI researchers.",
        "linkedin_url": "https://linkedin.com/in/sureshnambiar-healthbot",
    },
    {
        "id": "usr_023",
        "full_name": "Ruchika Agrawal",
        "email": "ruchika.a@pathologyai.com",
        "phone": "+91-9834567891",
        "organization": "PathologyAI",
        "role": "Computational Pathology Engineer",
        "experience_level": "mid",
        "detailed_profile": "Building digital pathology AI for cancer detection — whole slide image analysis, tissue segmentation, and grading using gigapixel images. Familiar with CLAM, HistoSSL, and attention-based MIL models. Worked on prostate and breast cancer classification pipelines validated against pathologist labels. Interested in AI-assisted pathology workflows and clinical validation of AI diagnostic tools.",
        "linkedin_url": "https://linkedin.com/in/ruchikaagrawal-pathology",
    },
    {
        "id": "usr_024",
        "full_name": "Dr. Farhan Sheikh",
        "email": "farhan.sheikh@mhealth-ai.org",
        "phone": "+91-9845678902",
        "organization": "mHealth AI Foundation",
        "role": "Global Health & AI Researcher",
        "experience_level": "senior",
        "detailed_profile": "Working at the intersection of public health and AI — building predictive models for disease surveillance, epidemic forecasting, and healthcare access in low-income communities. Worked with WHO and UNICEF on digital health projects in Southeast Asia. Interested in AI for malaria, TB, and maternal health. Advocate for open-source health AI and equitable access to diagnostic tools.",
        "linkedin_url": "https://linkedin.com/in/farhan-sheikh-globalhealth",
    },
    {
        "id": "usr_025",
        "full_name": "Anushka Dey",
        "email": "anushka.dey@mentalhealth.ai",
        "phone": "+91-9856789013",
        "organization": "MindAI",
        "role": "AI Product Manager",
        "experience_level": "mid",
        "detailed_profile": "PM at a mental health AI startup building conversational therapy support tools. Managing the roadmap for a CBT-based chatbot with 30k active users. Deep interest in the ethics of AI in mental health — safety guardrails, escalation protocols, and clinical validation. Previously a psychologist before transitioning to tech. Looking to connect with mental health professionals, ethicists, and LLM engineers.",
        "linkedin_url": "https://linkedin.com/in/anushkadey-mhtech",
    },
    {
        "id": "usr_026",
        "full_name": "Harish Venkat",
        "email": "harish.v@retinalai.com",
        "phone": "+91-9867890124",
        "organization": "RetinalAI",
        "role": "Medical Imaging ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building AI for diabetic retinopathy screening deployed in rural vision centres. Our model processes fundus images on low-cost Android devices without internet connectivity. Developed custom quantised CNN models running at 2W on Snapdragon. Validated against senior ophthalmologists in clinical trials. Interested in edge AI for healthcare, ophthalmology AI, and mHealth deployments.",
        "linkedin_url": "https://linkedin.com/in/harishvenkat-retinal",
    },
    {
        "id": "usr_027",
        "full_name": "Nisha Kapoor",
        "email": "nisha.kapoor@drugdiscovery.ai",
        "phone": "+91-9878901235",
        "organization": "MoleculeAI",
        "role": "AI Drug Discovery Scientist",
        "experience_level": "expert",
        "detailed_profile": "Applying graph neural networks and generative models to drug discovery. Building molecular generation pipelines for novel antibiotic candidates. Background in organic chemistry and cheminformatics. Experience with RDKit, DeepChem, and diffusion-based molecular generative models. Collaborating with pharma companies on AI-assisted lead optimisation. Looking to connect with medicinal chemists and computational chemists.",
        "linkedin_url": "https://linkedin.com/in/nishakapoor-drugai",
    },
    {
        "id": "usr_028",
        "full_name": "Rajesh Menon",
        "email": "rajesh.m@surgicalai.in",
        "phone": "+91-9889012346",
        "organization": "SurgicalAI",
        "role": "Surgical AI Researcher",
        "experience_level": "mid",
        "detailed_profile": "Building AI for surgical workflow analysis — activity recognition, instrument tracking, and skills assessment from OR video feeds. Trained transformer models on 1000+ hours of laparoscopic surgery video. Collaborating with surgeons to build AI-assisted training tools for junior doctors. Interested in computer vision for medicine, human-AI teaming in clinical settings, and simulation for surgical training.",
        "linkedin_url": "https://linkedin.com/in/rajeshmenon-surgicalai",
    },
    {
        "id": "usr_029",
        "full_name": "Dr. Leela Prasad",
        "email": "leela.prasad@neuroai.in",
        "phone": "+91-9890123457",
        "organization": "NeuroAI Lab",
        "role": "Neurologist & AI Researcher",
        "experience_level": "expert",
        "detailed_profile": "Neurologist and AI researcher at NIMHANS Bangalore. Applying ML to EEG and brain imaging for epilepsy diagnosis and seizure prediction. Developing wearable EEG devices with on-device inference for real-time monitoring. Interested in BCIs, neurodegenerative disease early detection, and AI tools for neurologists in tier-3 settings. Seeking ML engineers interested in neuroscience applications.",
        "linkedin_url": "https://linkedin.com/in/drleelapprasad-neuroai",
    },
    {
        "id": "usr_030",
        "full_name": "Swati Jain",
        "email": "swati.jain@healthdata.org",
        "phone": "+91-9801234568",
        "organization": "National Health Stack",
        "role": "Health Data Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building data pipelines and governance frameworks for the national health data exchange. Expertise in FHIR R4, HL7, and health data interoperability. Working on anonymisation pipelines to enable secondary use of patient data for research. Background in public health informatics and data engineering (Spark, dbt). Interested in health data ecosystems, privacy-preserving analytics, and DPDP compliance.",
        "linkedin_url": "https://linkedin.com/in/swatijain-healthdata",
    },

    # ── AgriTech (31–42) ──────────────────────────────────────────────────────
    {
        "id": "usr_031",
        "full_name": "Sunil Pawar",
        "email": "sunil.pawar@cropvision.ag",
        "phone": "+91-9712345679",
        "organization": "CropVision",
        "role": "AgriTech ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building satellite and drone imagery analysis systems for precision agriculture. Developed crop health monitoring models detecting nutrient deficiency and disease stress in soybean and cotton fields across Maharashtra. Using multi-spectral imaging and NDVI analysis. Familiar with QGIS, Google Earth Engine, and PyTorch segmentation models. Interested in sustainable farming, remote sensing, and food security.",
        "linkedin_url": "https://linkedin.com/in/sunilpawar-agri",
    },
    {
        "id": "usr_032",
        "full_name": "Geetha Raman",
        "email": "geetha.r@soilsense.io",
        "phone": "+91-9723456790",
        "organization": "SoilSense",
        "role": "IoT & ML Engineer",
        "experience_level": "mid",
        "detailed_profile": "Designing IoT sensor networks for real-time soil health monitoring — moisture, pH, nitrogen, and temperature. Built ML models to generate actionable fertiliser and irrigation recommendations from sensor data. Deployed 500+ sensor nodes across farms in Tamil Nadu and Andhra Pradesh. Background in embedded systems and data science. Looking to connect with agronomists, farmers, and sustainability researchers.",
        "linkedin_url": "https://linkedin.com/in/geetharaman-iot",
    },
    {
        "id": "usr_033",
        "full_name": "Mohan Krishnamurthy",
        "email": "mohan.k@agri-advisory.ai",
        "phone": "+91-9734567891",
        "organization": "AgriAdvisory AI",
        "role": "Co-founder",
        "experience_level": "expert",
        "detailed_profile": "Co-founder of AgriAdvisory AI, a platform delivering personalised farming advice to 80k smallholder farmers via WhatsApp in Kannada, Telugu, and Hindi. Built LLM-powered advisory systems grounded in agronomic databases. Previously at ICRISAT and World Bank agricultural programs. Deep understanding of smallholder farmer needs, extension services, and agri-value chains. Raising Series A.",
        "linkedin_url": "https://linkedin.com/in/mohankrishnamurthy-agri",
    },
    {
        "id": "usr_034",
        "full_name": "Lakshmi Narayanan",
        "email": "lakshmi.n@plantpathology.ai",
        "phone": "+91-9745678902",
        "organization": "PlantDoctor AI",
        "role": "Plant Pathology AI Researcher",
        "experience_level": "senior",
        "detailed_profile": "Developing AI-powered crop disease diagnosis tools — identifying 200+ plant diseases from smartphone photos. Trained on 1.2M labelled disease images from 15 crop types. Building an offline-capable app for farmers in low-connectivity areas. Collaborating with ICAR and state agricultural universities. Interested in AI for food security, phytopathology, and mobile-first rural tech.",
        "linkedin_url": "https://linkedin.com/in/lakshminarayanan-plant",
    },
    {
        "id": "usr_035",
        "full_name": "Pradeep Choudhary",
        "email": "pradeep.c@smartirrigation.tech",
        "phone": "+91-9756789013",
        "organization": "SmartIrrigation Tech",
        "role": "Water Technology Engineer",
        "experience_level": "mid",
        "detailed_profile": "Building AI-driven precision irrigation systems that reduce water usage by 35% while maintaining crop yield. Combining weather forecasting models, soil moisture sensors, and crop water demand models. Deployed in 200 farms across Rajasthan. Background in hydrology and agricultural engineering. Interested in climate-smart agriculture, water scarcity solutions, and sustainable food systems.",
        "linkedin_url": "https://linkedin.com/in/pradeepchoudhary-water",
    },
    {
        "id": "usr_036",
        "full_name": "Anjali Sharma",
        "email": "anjali.s@supplychain-agri.com",
        "phone": "+91-9767890125",
        "organization": "AgriChain",
        "role": "Supply Chain Data Scientist",
        "experience_level": "mid",
        "detailed_profile": "Applying ML to agricultural supply chains — demand forecasting, price prediction, and spoilage reduction for perishable produce. Built time series models predicting tomato prices 4 weeks ahead with 82% accuracy. Interested in connecting farmers directly with markets, reducing middlemen, and making agri-markets transparent. Background in operations research and agricultural economics.",
        "linkedin_url": "https://linkedin.com/in/anjalishm-agrichain",
    },
    {
        "id": "usr_037",
        "full_name": "Vivek Patel",
        "email": "vivek.p@aquatech.farm",
        "phone": "+91-9778901236",
        "organization": "AquaTech Farms",
        "role": "Aquaculture AI Engineer",
        "experience_level": "senior",
        "detailed_profile": "Applying computer vision and ML to fish farming — monitoring fish biomass, detecting disease, and optimising feed delivery through underwater cameras. Built a real-time fish counting and sizing system deployed in 30 shrimp farms in Andhra Pradesh. Interested in aquaculture innovation, blue economy, and sustainable protein production. Looking for collaborators in aquaculture, marine biology, and vision AI.",
        "linkedin_url": "https://linkedin.com/in/vivekpatel-aqua",
    },
    {
        "id": "usr_038",
        "full_name": "Radhika Nair",
        "email": "radhika.nair@agri-finance.ai",
        "phone": "+91-9789012346",
        "organization": "AgriFin AI",
        "role": "Agri-Fintech Product Manager",
        "experience_level": "mid",
        "detailed_profile": "Building AI-powered credit scoring for smallholder farmers using alternative data — satellite imagery, crop history, weather patterns, and mobile usage. Managing a product used by 3 NBFCs to disburse crop loans to 25k unbanked farmers. Background in rural banking and data science. Interested in financial inclusion, agri-credit, and blended finance for the agricultural sector.",
        "linkedin_url": "https://linkedin.com/in/radhikanair-agrifin",
    },
    {
        "id": "usr_039",
        "full_name": "Subramaniam Iyer",
        "email": "subbu.iyer@agrorobotics.io",
        "phone": "+91-9890234567",
        "organization": "AgroRobotics",
        "role": "Robotics Engineer",
        "experience_level": "senior",
        "detailed_profile": "Designing autonomous agricultural robots for seeding, weeding, and harvesting. Our team built a solar-powered weeding robot that reduces herbicide use by 70%. Deep expertise in ROS2, path planning, manipulator control, and field navigation. Previously at Boston Dynamics and Mahindra Research Valley. Looking to connect with farmers, agronomy experts, and hardware investors.",
        "linkedin_url": "https://linkedin.com/in/subramaniamiyer-agro",
    },
    {
        "id": "usr_040",
        "full_name": "Kamla Devi",
        "email": "kamla.devi@farmerhive.in",
        "phone": "+91-9801345678",
        "organization": "FarmerHive",
        "role": "Rural Tech Entrepreneur",
        "experience_level": "expert",
        "detailed_profile": "Founder of FarmerHive, a cooperative marketplace connecting 12k women farmers in MP and UP with urban buyers. Built voice-first AI product for feature phone users in Hindi and Bhojpuri. Worked 10 years with SEWA and NABARD before launching. Deeply understand the ground realities of smallholder farming. Looking for tech partners, impact investors, and government collaborators.",
        "linkedin_url": "https://linkedin.com/in/kamladevi-farmerhive",
    },
    {
        "id": "usr_041",
        "full_name": "Dinesh Kumar",
        "email": "dinesh.kumar@agrisat.space",
        "phone": "+91-9812456789",
        "organization": "AgriSat",
        "role": "Remote Sensing Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Analysing multispectral and SAR satellite data for crop area mapping, yield estimation, and flood impact assessment. Built a national crop monitoring dashboard used by Ministry of Agriculture. Familiar with Sentinel-1/2, Landsat, and MODIS datasets. Experience with GEE, GDAL, and deep learning for geospatial analysis. Interested in climate adaptation, food security forecasting, and open satellite data.",
        "linkedin_url": "https://linkedin.com/in/dineshkumar-rs",
    },
    {
        "id": "usr_042",
        "full_name": "Preethi Sundar",
        "email": "preethi.s@climatesmart.ag",
        "phone": "+91-9823567890",
        "organization": "ClimaSmart Agri",
        "role": "Climate Adaptation Researcher",
        "experience_level": "mid",
        "detailed_profile": "Researching climate-resilient crop varieties and farming practices using ML and climate models. Building tools that help farmers choose crops suited to changing rainfall and temperature patterns. Partnership with CGIAR and ICRISAT. Background in agronomy and data science. Interested in climate change adaptation, agroforestry, and technology for smallholder resilience.",
        "linkedin_url": "https://linkedin.com/in/preethisundar-climate",
    },

    # ── Fintech / Blockchain (43–52) ───────────────────────────────────────────
    {
        "id": "usr_043",
        "full_name": "Akash Gupta",
        "email": "akash.gupta@fraudshield.io",
        "phone": "+91-9734678901",
        "organization": "FraudShield",
        "role": "Fraud Detection ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building real-time fraud detection systems processing 5M transactions/day. Specialise in graph neural networks for detecting money laundering networks, anomaly detection on transactional data, and online learning systems that adapt to new fraud patterns. Previously at Razorpay and Paytm. Interested in connecting with ML engineers in payments, risk, and financial crime.",
        "linkedin_url": "https://linkedin.com/in/akashgupta-fraud",
    },
    {
        "id": "usr_044",
        "full_name": "Riya Bahl",
        "email": "riya.bahl@creditml.in",
        "phone": "+91-9745678903",
        "organization": "CreditML",
        "role": "Credit Risk Data Scientist",
        "experience_level": "mid",
        "detailed_profile": "Building credit scoring models for MSME lending using alternative data — GST returns, bank statements, and social data. Designed a feature engineering pipeline that improved GINI coefficient by 12 points over bureau scores alone. Familiar with XGBoost, SHAP explainability, and RBI model governance guidelines. Interested in financial inclusion, responsible lending, and credit for the underserved.",
        "linkedin_url": "https://linkedin.com/in/riyabahl-credit",
    },
    {
        "id": "usr_045",
        "full_name": "Nikhil Rao",
        "email": "nikhil.rao@defiprotocol.io",
        "phone": "+91-9756790123",
        "organization": "DeFi Protocol Labs",
        "role": "Blockchain Engineer",
        "experience_level": "senior",
        "detailed_profile": "Building DeFi protocols on Ethereum and Solana — smart contracts, liquidity pools, and yield optimisation strategies. Deep expertise in Solidity, Anchor framework, and Rust. Built an on-chain ML inference system for dynamic interest rate adjustment. Interested in the convergence of AI and Web3, tokenised real-world assets, and decentralised identity.",
        "linkedin_url": "https://linkedin.com/in/nikhilrao-defi",
    },
    {
        "id": "usr_046",
        "full_name": "Sheetal Mehta",
        "email": "sheetal.mehta@regtech.ai",
        "phone": "+91-9767901234",
        "organization": "RegTech AI",
        "role": "Regulatory AI Specialist",
        "experience_level": "expert",
        "detailed_profile": "Using NLP and ML to automate regulatory compliance — parsing RBI circulars, SEBI regulations, and mapping them to internal policies. Built a regulatory change monitoring system used by 3 large banks. Background in law and computer science. Interested in LegalTech, RegTech, compliance automation, and the intersection of law and AI in financial services.",
        "linkedin_url": "https://linkedin.com/in/sheetalmehta-regtech",
    },
    {
        "id": "usr_047",
        "full_name": "Aman Chopra",
        "email": "aman.chopra@insurtech.ai",
        "phone": "+91-9778012345",
        "organization": "InsurTech AI",
        "role": "Actuarial Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Applying ML to insurance underwriting, claims processing, and telematics-based motor insurance pricing. Built a real-time claims fraud detection system reducing fraudulent payouts by 23%. Familiar with survival analysis, GLMs, and gradient boosting for actuarial modelling. Interested in parametric insurance, climate risk modelling, and using AI to expand insurance access in India.",
        "linkedin_url": "https://linkedin.com/in/amanchopra-insur",
    },
    {
        "id": "usr_048",
        "full_name": "Simran Kaur",
        "email": "simran.kaur@wealthai.in",
        "phone": "+91-9789123456",
        "organization": "WealthAI",
        "role": "Quantitative Researcher",
        "experience_level": "mid",
        "detailed_profile": "Building quantitative models for portfolio optimisation, factor investing, and market microstructure analysis. Developed an RL-based portfolio rebalancing agent outperforming the Nifty 50 by 3% annually in backtesting. Background in statistics, financial engineering, and Python. Interested in ML for capital markets, alternative data, and AI-driven investment strategies.",
        "linkedin_url": "https://linkedin.com/in/simrankaur-quant",
    },
    {
        "id": "usr_049",
        "full_name": "Rajiv Nair",
        "email": "rajiv.nair@cbdc-research.in",
        "phone": "+91-9890345678",
        "organization": "RBI Innovation Hub",
        "role": "CBDC Research Engineer",
        "experience_level": "senior",
        "detailed_profile": "Working on technical research for India's Central Bank Digital Currency (CBDC/e-Rupee) — architecture, scalability, and privacy design. Background in distributed systems, cryptography, and payments. Previously at NPCI, built infrastructure for UPI at scale. Interested in digital public infrastructure, financial system resilience, and the design of fair monetary systems.",
        "linkedin_url": "https://linkedin.com/in/rajivnair-cbdc",
    },
    {
        "id": "usr_050",
        "full_name": "Deepa Subramaniam",
        "email": "deepa.s@embedded-finance.io",
        "phone": "+91-9801456789",
        "organization": "EmbedFin",
        "role": "API Product Manager",
        "experience_level": "mid",
        "detailed_profile": "Building embedded finance APIs — BNPL, pay-later at checkout, and credit-as-a-service for e-commerce and SaaS platforms. Managed a platform processing 1M transactions/month. Deep understanding of BNPL economics, credit risk, and partner integration. Interested in the next wave of fintech, B2B payments, and financial infrastructure for emerging markets.",
        "linkedin_url": "https://linkedin.com/in/deepasubra-fin",
    },
    {
        "id": "usr_051",
        "full_name": "Harshit Bansal",
        "email": "harshit.bansal@kyc-ai.com",
        "phone": "+91-9812567890",
        "organization": "KYC AI",
        "role": "Document AI Engineer",
        "experience_level": "mid",
        "detailed_profile": "Building OCR and document intelligence systems for financial KYC — extracting information from Aadhaar, PAN, and bank statements. Trained custom vision-transformer models for Indian document understanding. Processing 500k documents monthly. Interested in document AI, identity verification, and AI in regulated industries.",
        "linkedin_url": "https://linkedin.com/in/harshitbansal-kyc",
    },
    {
        "id": "usr_052",
        "full_name": "Pallavi Singh",
        "email": "pallavi.singh@payments-ml.com",
        "phone": "+91-9823678901",
        "organization": "PayML",
        "role": "Payments ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Optimising payment acceptance rates using ML — routing transactions to the most likely successful processor, reducing decline rates by 18%. Built real-time feature engineering pipelines on Kafka for payment intelligence. Previously at PhonePe and Stripe India. Interested in ML for payment systems, transaction reliability, and AI in financial infrastructure.",
        "linkedin_url": "https://linkedin.com/in/pallavisingh-pay",
    },

    # ── Climate Tech (53–62) ───────────────────────────────────────────────────
    {
        "id": "usr_053",
        "full_name": "Karthik Subramanian",
        "email": "karthik.s@carbontrace.earth",
        "phone": "+91-9734789012",
        "organization": "CarbonTrace",
        "role": "Climate Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Building ML systems for carbon footprint estimation and lifecycle analysis across supply chains. Developed satellite-based deforestation monitoring models for REDD+ carbon credit verification. Familiar with climate modelling (CMIP6), carbon accounting standards, and ESG data. Interested in carbon markets, climate finance, and using AI to accelerate decarbonisation.",
        "linkedin_url": "https://linkedin.com/in/karthiksubramanian-carbon",
    },
    {
        "id": "usr_054",
        "full_name": "Ishaan Verma",
        "email": "ishaan.verma@gridoptimize.energy",
        "phone": "+91-9745789013",
        "organization": "GridOptimize",
        "role": "Energy Systems ML Engineer",
        "experience_level": "mid",
        "detailed_profile": "Applying ML to energy grid optimisation — renewable energy forecasting, demand response, and battery storage management. Built a solar irradiance forecasting model reducing curtailment by 15% for a 100MW solar farm. Familiar with reinforcement learning for grid control and digital twin modelling. Interested in clean energy transition, microgrids, and AI for sustainable energy systems.",
        "linkedin_url": "https://linkedin.com/in/ishaanverma-energy",
    },
    {
        "id": "usr_055",
        "full_name": "Sonali Bhatt",
        "email": "sonali.bhatt@wastetech.ai",
        "phone": "+91-9756901234",
        "organization": "WasteTech AI",
        "role": "Circular Economy Engineer",
        "experience_level": "mid",
        "detailed_profile": "Using computer vision and route optimisation ML for smart waste management in urban India. Built a waste segregation robot using vision AI deployed in 5 municipalities. Developed waste collection route optimisation reducing fuel costs by 30%. Interested in circular economy, urban sustainability, and applying AI to environmental challenges.",
        "linkedin_url": "https://linkedin.com/in/somalibhatt-waste",
    },
    {
        "id": "usr_056",
        "full_name": "Arun Nair",
        "email": "arun.nair@evtech.in",
        "phone": "+91-9767012345",
        "organization": "EVTech India",
        "role": "EV Battery ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Working on battery management systems and state-of-health prediction for electric vehicle batteries using ML. Developed anomaly detection models for EV charging infrastructure. Background in electrochemistry and data science. Interested in EV adoption in India, second-life battery reuse, and AI for sustainable transportation.",
        "linkedin_url": "https://linkedin.com/in/arunnair-ev",
    },
    {
        "id": "usr_057",
        "full_name": "Deepak Sharma",
        "email": "deepak.s@buildingai.green",
        "phone": "+91-9778123456",
        "organization": "GreenBuild AI",
        "role": "Building Energy Engineer",
        "experience_level": "mid",
        "detailed_profile": "Reducing energy consumption in commercial buildings using ML-based HVAC optimisation, occupancy prediction, and smart lighting control. Deployed building energy management systems in 80 commercial buildings reducing energy bills by 25%. Familiar with BMS integration, BACnet protocols, and digital twin technology. Interested in smart buildings, green construction, and urban climate action.",
        "linkedin_url": "https://linkedin.com/in/deepaksharma-green",
    },
    {
        "id": "usr_058",
        "full_name": "Aruna Krishnan",
        "email": "aruna.krishnan@oceanai.org",
        "phone": "+91-9789234567",
        "organization": "Ocean AI Foundation",
        "role": "Marine Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Using ML and ocean sensor networks to monitor coral reef health, plastic pollution distribution, and fish stock levels. Deployed autonomous underwater vehicles with on-board ML for ocean surveying. Collaborating with WWF and IUCN on marine conservation AI tools. Interested in ocean health, blue carbon, and technology for marine biodiversity preservation.",
        "linkedin_url": "https://linkedin.com/in/arunakrishnan-ocean",
    },
    {
        "id": "usr_059",
        "full_name": "Rohit Bhargava",
        "email": "rohit.b@airquality.ai",
        "phone": "+91-9890456789",
        "organization": "AirQuality AI",
        "role": "Environmental Data Scientist",
        "experience_level": "mid",
        "detailed_profile": "Building air quality prediction models integrating satellite data, ground sensors, and weather forecasts. Deployed hyperlocal AQI prediction for 15 Indian cities helping 2M users plan outdoor activities. Collaborating with CPCB on pollution source attribution using ML. Interested in environmental health, smart cities, and citizen science data.",
        "linkedin_url": "https://linkedin.com/in/rohitbhargava-air",
    },
    {
        "id": "usr_060",
        "full_name": "Maya Pillai",
        "email": "maya.pillai@climatemodels.in",
        "phone": "+91-9801567890",
        "organization": "IITM Pune",
        "role": "Climate Modelling Researcher",
        "experience_level": "expert",
        "detailed_profile": "Applying deep learning to improve regional climate model downscaling and extreme weather event prediction. Published in Nature Climate Change. Working on AI emulators for climate models that run 1000x faster than physics-based simulations. Interested in climate change science, extreme weather prediction, and ML for Earth system modelling.",
        "linkedin_url": "https://linkedin.com/in/mayapillai-climate",
    },
    {
        "id": "usr_061",
        "full_name": "Sandeep Goel",
        "email": "sandeep.g@hydro-ai.com",
        "phone": "+91-9812678901",
        "organization": "HydroAI",
        "role": "Water Resource Engineer",
        "experience_level": "senior",
        "detailed_profile": "Applying ML to hydrological modelling — flood prediction, groundwater level forecasting, and basin runoff estimation. Built a real-time flood early warning system for three Himalayan river basins. Collaborated with CWC and state disaster management authorities. Interested in climate adaptation, disaster preparedness, and AI for water security.",
        "linkedin_url": "https://linkedin.com/in/sandeepgoel-hydro",
    },
    {
        "id": "usr_062",
        "full_name": "Kavitha Mani",
        "email": "kavitha.m@cleantech-vc.com",
        "phone": "+91-9823789012",
        "organization": "CleanTech Capital",
        "role": "Investment Analyst",
        "experience_level": "mid",
        "detailed_profile": "Analyst at a climate-focused VC fund investing in Indian cleantech startups — solar, EVs, agri-tech, and carbon markets. Background in mechanical engineering and finance. Evaluating AI-driven climate solutions for portfolio investment. Interested in connecting with climate tech founders, impact entrepreneurs, and cleantech ecosystem builders.",
        "linkedin_url": "https://linkedin.com/in/kavithamani-vc",
    },

    # ── Founders & Entrepreneurs (63–72) ──────────────────────────────────────
    {
        "id": "usr_063",
        "full_name": "Nitin Agarwal",
        "email": "nitin.agarwal@aistart.vc",
        "phone": "+91-9834890123",
        "organization": "AIStart Ventures",
        "role": "Angel Investor & Mentor",
        "experience_level": "expert",
        "detailed_profile": "Angel investor and mentor with 12 investments in early-stage AI startups across healthcare, agri, and edtech. Ex-founder of two SaaS companies (one acquired). Helps founders with product-market fit, fundraising strategy, and scaling. Looking to meet ambitious founders applying AI to hard problems in India. Particularly interested in AI for Bharat — vernacular, offline-first, and high-impact.",
        "linkedin_url": "https://linkedin.com/in/nitinagarwal-angel",
    },
    {
        "id": "usr_064",
        "full_name": "Prerna Gupta",
        "email": "prerna.gupta@edtech-ai.com",
        "phone": "+91-9845901234",
        "organization": "LearnAI",
        "role": "Founder & CEO",
        "experience_level": "expert",
        "detailed_profile": "Founded LearnAI, an adaptive learning platform using LLMs to personalise K-12 education in regional languages. 200k students across 5 states. Previously teacher and education researcher. Passionate about closing the urban-rural education gap using AI. Raising Series A. Looking for EdTech enthusiasts, learning scientists, and impact investors to connect.",
        "linkedin_url": "https://linkedin.com/in/prernagupta-edtech",
    },
    {
        "id": "usr_065",
        "full_name": "Gaurav Khanna",
        "email": "gaurav.khanna@legaltech.ai",
        "phone": "+91-9856012345",
        "organization": "LexAI",
        "role": "Co-founder & CTO",
        "experience_level": "expert",
        "detailed_profile": "Building AI-powered legal research and contract analysis tools for Indian law firms and in-house teams. Our LLM is fine-tuned on Indian case law and statutes. 80 law firm customers in 18 months. Background in CS and law. Previously at Khaitan & Co and BCG. Looking to connect with legal professionals, GCs, and other legal tech founders.",
        "linkedin_url": "https://linkedin.com/in/gauravkhanna-lex",
    },
    {
        "id": "usr_066",
        "full_name": "Priya Chatterjee",
        "email": "priya.c@vernacular.ai",
        "phone": "+91-9867123456",
        "organization": "Vernacular AI",
        "role": "Founder",
        "experience_level": "expert",
        "detailed_profile": "Building voice AI products for India in 15 regional languages. Our platform powers IVR bots for rural government services used by 3M citizens monthly. Background in linguistics and ML. Previously at Microsoft Research India. Passionate about language technology for underserved communities, multilingual AI, and inclusive tech policy.",
        "linkedin_url": "https://linkedin.com/in/priyachatterjee-vernacular",
    },
    {
        "id": "usr_067",
        "full_name": "Sameer Malhotra",
        "email": "sameer.m@saas-ai.in",
        "phone": "+91-9878234567",
        "organization": "SaaS Builder",
        "role": "Serial Entrepreneur",
        "experience_level": "expert",
        "detailed_profile": "Third startup, building AI-native B2B SaaS for supply chain visibility. Two previous exits. Strong in go-to-market, enterprise sales, and scaling India-first SaaS globally. Deep network in Tier-1 VCs and Indian enterprise customers. Looking to meet early-stage AI founders, potential co-founders for my next venture, and enterprise AI buyers.",
        "linkedin_url": "https://linkedin.com/in/sameermalhotra-saas",
    },
    {
        "id": "usr_068",
        "full_name": "Anoushka Mehrotra",
        "email": "anoushka.m@social-ai.org",
        "phone": "+91-9889345678",
        "organization": "Social Impact AI",
        "role": "Social Entrepreneur",
        "experience_level": "senior",
        "detailed_profile": "Using AI to solve social problems — built a job-matching platform for blue-collar workers using skill assessment AI, connecting 50k workers with employers in 6 cities. Background in social work and data science. Interested in AI for livelihoods, skill development, gig economy, and inclusive growth. Looking for CSR partners, government collaborators, and impact investors.",
        "linkedin_url": "https://linkedin.com/in/anoushkamehrotra-social",
    },
    {
        "id": "usr_069",
        "full_name": "Ravi Shankar",
        "email": "ravi.shankar@spacetech.in",
        "phone": "+91-9890456780",
        "organization": "StarOrbit India",
        "role": "Space Tech Founder",
        "experience_level": "expert",
        "detailed_profile": "Co-founder of StarOrbit, building small satellite platforms and Earth observation AI services. Background in aerospace engineering and deep learning. Building a constellation for precision agriculture and disaster management monitoring. ISRO collaborator. Looking for ML engineers interested in space applications, remote sensing, and satellite data processing.",
        "linkedin_url": "https://linkedin.com/in/ravishankar-space",
    },
    {
        "id": "usr_070",
        "full_name": "Aparna Sinha",
        "email": "aparna.sinha@hr-ai.io",
        "phone": "+91-9801567891",
        "organization": "TalentAI",
        "role": "HR Tech Founder",
        "experience_level": "senior",
        "detailed_profile": "Building AI-powered talent intelligence platform — job description generation, skill gap analysis, and interview question personalisation. Used by 150 companies for structured hiring. Background in HR and product management. Former CPO at an HR SaaS unicorn. Interested in the future of work, skills economy, AI in HR, and ethical hiring tools.",
        "linkedin_url": "https://linkedin.com/in/aparnasinha-hr",
    },
    {
        "id": "usr_071",
        "full_name": "Tarun Bajaj",
        "email": "tarun.bajaj@retailai.com",
        "phone": "+91-9812678902",
        "organization": "RetailAI",
        "role": "Retail Tech Founder",
        "experience_level": "expert",
        "detailed_profile": "Founded RetailAI, building AI for India's kirana store ecosystem — demand forecasting, inventory optimisation, and dynamic pricing for 20k small retailers. Background in FMCG distribution and ML. Backed by a strategic FMCG conglomerate. Looking for retail industry experts, FMCG partners, and ML engineers interested in retail intelligence.",
        "linkedin_url": "https://linkedin.com/in/tarunbajaj-retail",
    },
    {
        "id": "usr_072",
        "full_name": "Indira Krishnaswamy",
        "email": "indira.k@constructionai.in",
        "phone": "+91-9823789013",
        "organization": "BuildAI",
        "role": "PropTech Entrepreneur",
        "experience_level": "senior",
        "detailed_profile": "Applying AI to construction and real estate — site progress monitoring using drone imagery, cost overrun prediction, and quality inspection automation. Built AI tools used in 500 construction projects worth Rs 2000 Cr. Background in civil engineering and computer vision. Interested in smart infrastructure, PropTech innovation, and AI for the built environment.",
        "linkedin_url": "https://linkedin.com/in/indirakrishnaswamy-build",
    },

    # ── Researchers & Academics (73–82) ───────────────────────────────────────
    {
        "id": "usr_073",
        "full_name": "Prof. Mahesh Deshpande",
        "email": "mahesh.deshpande@iitk.ac.in",
        "phone": "+91-9734890123",
        "organization": "IIT Kanpur",
        "role": "Associate Professor, CS",
        "experience_level": "expert",
        "detailed_profile": "Researching program synthesis, automated reasoning, and neural-symbolic AI. Published 40+ papers at top venues. Running the AI for Code lab at IITK — working on LLMs that understand and generate formally verified code. Advising 6 PhD students. Consulting with startups on AI architectures. Looking for industry partnerships and PhD students.",
        "linkedin_url": "https://linkedin.com/in/prof-maheshd-iitk",
    },
    {
        "id": "usr_074",
        "full_name": "Dr. Zainab Mirza",
        "email": "zainab.mirza@islamia-ai.edu",
        "phone": "+91-9745901234",
        "organization": "Jamia Millia Islamia",
        "role": "Assistant Professor & NLP Researcher",
        "experience_level": "senior",
        "detailed_profile": "Researching NLP for low-resource languages — Urdu, Kashmiri, and Sindhi. Building language datasets, benchmark tasks, and multilingual models for South Asian languages. Collaborating with TDIL for language technology standardisation. Interested in linguistic diversity in AI, multilingual benchmarks, and decolonising NLP research.",
        "linkedin_url": "https://linkedin.com/in/zainabmirza-nlp",
    },
    {
        "id": "usr_075",
        "full_name": "Rohan Kulkarni",
        "email": "rohan.kulkarni@bits-pilani.ac.in",
        "phone": "+91-9756012345",
        "organization": "BITS Pilani",
        "role": "PhD Student, AI Safety",
        "experience_level": "junior",
        "detailed_profile": "Researching AI safety and alignment — specifically interpretability methods for understanding LLM internal representations. Working on mechanistic interpretability techniques to detect deceptive reasoning in large models. Active in the AI safety community, EA forums, and MATS programme. Looking for researchers in interpretability, red-teaming, and AI governance.",
        "linkedin_url": "https://linkedin.com/in/rohankulkarni-safety",
    },
    {
        "id": "usr_076",
        "full_name": "Dr. Preeti Agarwal",
        "email": "preeti.agarwal@nimhans.ac.in",
        "phone": "+91-9767123456",
        "organization": "NIMHANS",
        "role": "Computational Neuroscientist",
        "experience_level": "expert",
        "detailed_profile": "Researching neural correlates of decision-making and memory using fMRI and ML. Applying deep learning to decode brain states and predict cognitive performance. Running the NeuroDecoding lab at NIMHANS. Interested in BCIs, cognitive enhancement, neurotech, and the overlap between AI architectures and biological neural circuits.",
        "linkedin_url": "https://linkedin.com/in/drpreetiagarwal-neuro",
    },
    {
        "id": "usr_077",
        "full_name": "Shyam Patel",
        "email": "shyam.patel@iisc.ac.in",
        "phone": "+91-9778234567",
        "organization": "IISc Bangalore",
        "role": "Postdoctoral Researcher, Robotics",
        "experience_level": "senior",
        "detailed_profile": "Postdoc at IISc working on learning-based robot manipulation — combining sim-to-real transfer, imitation learning, and force feedback for dexterous manipulation. Background in mechanical engineering and deep learning. Published at ICRA and CoRL. Interested in humanoid robots, foundation models for robotics, and real-world robot deployment.",
        "linkedin_url": "https://linkedin.com/in/shyampatel-robotics",
    },
    {
        "id": "usr_078",
        "full_name": "Dr. Anita Rao",
        "email": "anita.rao@xlri.ac.in",
        "phone": "+91-9789345678",
        "organization": "XLRI Jamshedpur",
        "role": "Organisational Behaviour Researcher",
        "experience_level": "expert",
        "detailed_profile": "Studying AI adoption and human-AI collaboration in organisations. Research focuses on trust, autonomy, and employee wellbeing in AI-augmented workplaces. Published in Nature Human Behaviour and Harvard Business Review. Consulting Fortune 500 companies on responsible AI implementation. Interested in the socio-technical aspects of AI deployment.",
        "linkedin_url": "https://linkedin.com/in/dranita-rao-xlri",
    },
    {
        "id": "usr_079",
        "full_name": "Vijay Krishnan",
        "email": "vijay.krishnan@iimb.ac.in",
        "phone": "+91-9890567890",
        "organization": "IIM Bangalore",
        "role": "Professor, Technology Management",
        "experience_level": "expert",
        "detailed_profile": "Researching AI strategy, platform economics, and digital transformation. Advising Indian government on AI policy and published extensively on platform regulation. Running the Centre for AI Strategy at IIMB. Seeking collaboration with industry on AI governance, responsible AI implementation, and the economic impact of AI in emerging markets.",
        "linkedin_url": "https://linkedin.com/in/vijaykrishnan-iimb",
    },
    {
        "id": "usr_080",
        "full_name": "Neha Sharma",
        "email": "neha.sharma@iiit-h.ac.in",
        "phone": "+91-9801678901",
        "organization": "IIIT Hyderabad",
        "role": "PhD Student, Computer Vision",
        "experience_level": "junior",
        "detailed_profile": "Third-year PhD at IIIT-H working on 3D scene understanding and neural radiance fields (NeRF). Building methods for autonomous navigation in unstructured outdoor environments. Interning at ISRO for remote sensing applications. Looking for industry collaborators in autonomous vehicles, robotics, and AR/VR.",
        "linkedin_url": "https://linkedin.com/in/nehasharma-3dvision",
    },
    {
        "id": "usr_081",
        "full_name": "Dr. Sangeeta Nair",
        "email": "sangeeta.nair@tifr.res.in",
        "phone": "+91-9812789012",
        "organization": "TIFR Mumbai",
        "role": "Theoretical ML Researcher",
        "experience_level": "expert",
        "detailed_profile": "Theoretical foundations of machine learning — generalisation bounds, PAC learning, and the theory behind neural scaling laws. Published in COLT, NeurIPS, and ICML. Interested in bridging theory and practice, especially for LLMs. Open to collaborations with empirical ML researchers who want to ground their intuitions in formal theory.",
        "linkedin_url": "https://linkedin.com/in/sangeetanair-theory",
    },
    {
        "id": "usr_082",
        "full_name": "Arpit Mishra",
        "email": "arpit.mishra@cse-iitm.ac.in",
        "phone": "+91-9823890123",
        "organization": "IIT Madras",
        "role": "Research Associate, NLP",
        "experience_level": "junior",
        "detailed_profile": "Working on code generation and program repair using LLMs. Specifically researching how to make LLMs reliable for production-level code synthesis — handling edge cases, security vulnerabilities, and test generation. Part of the IITM NLP group. Looking to transition to industry research after my Masters. Open to internships and research collaborations in coding AI.",
        "linkedin_url": "https://linkedin.com/in/arpitmishra-code",
    },

    # ── Product, DevRel & Developer Experience (83–90) ────────────────────────
    {
        "id": "usr_083",
        "full_name": "Shalini Batra",
        "email": "shalini.batra@devrel.ai",
        "phone": "+91-9834901234",
        "organization": "AI Dev Community",
        "role": "Developer Advocate",
        "experience_level": "mid",
        "detailed_profile": "Developer advocate focused on making ML tools accessible to developers. Run workshops on LangChain, Hugging Face, and FastAPI across 20 Indian cities. YouTube channel with 50k subscribers on practical ML. Passionate about open-source ML, developer education, and building inclusive tech communities. Looking to connect with other DevRel folks and ML educators.",
        "linkedin_url": "https://linkedin.com/in/shalinibatra-devrel",
    },
    {
        "id": "usr_084",
        "full_name": "Ankit Verma",
        "email": "ankit.verma@product-ai.com",
        "phone": "+91-9845012345",
        "organization": "ProductAI",
        "role": "Senior Product Manager",
        "experience_level": "senior",
        "detailed_profile": "PM for AI features at a B2B SaaS company — managing the roadmap for an AI writing assistant used by 100k professionals. Strong in user research, experimentation, and translating ML capabilities into product features. Background in UX and psychology. Interested in AI UX patterns, measuring AI product value, and building trust in AI-powered products.",
        "linkedin_url": "https://linkedin.com/in/ankitverma-pm",
    },
    {
        "id": "usr_085",
        "full_name": "Pooja Mishra",
        "email": "pooja.mishra@ux-ai.design",
        "phone": "+91-9856123456",
        "organization": "UX for AI",
        "role": "AI UX Designer",
        "experience_level": "mid",
        "detailed_profile": "Designing human-AI interactions that feel natural and build appropriate trust. Researching UX patterns for LLM uncertainty, error recovery, and explainability. Portfolio includes AI-powered tools for legal, medical, and financial professionals. Interested in responsible AI design, inclusive UX, and the accessibility of AI tools for non-technical users.",
        "linkedin_url": "https://linkedin.com/in/poojamishra-aiux",
    },
    {
        "id": "usr_086",
        "full_name": "Rakesh Trivedi",
        "email": "rakesh.trivedi@b2b-saas.io",
        "phone": "+91-9867234567",
        "organization": "SaaSGrowth",
        "role": "Growth Product Manager",
        "experience_level": "senior",
        "detailed_profile": "Growth PM specialising in AI-powered personalisation for B2B SaaS. Built a recommendation engine increasing feature adoption by 45%. Deeply experienced in product analytics, funnel optimisation, and experimentation at scale. Run a popular newsletter on AI product management with 15k subscribers. Looking to connect with product folks building AI-native products.",
        "linkedin_url": "https://linkedin.com/in/rakештrivedi-growth",
    },
    {
        "id": "usr_087",
        "full_name": "Varsha Kumari",
        "email": "varsha.k@ml-community.in",
        "phone": "+91-9878345678",
        "organization": "ML India",
        "role": "Community Builder & ML Engineer",
        "experience_level": "mid",
        "detailed_profile": "Organise PyData Pune and WiML India chapter. ML engineer by day, community builder by night. Passionate about making ML careers accessible to women and people from tier-2 and tier-3 cities. Mentoring 30+ early-career ML practitioners. Looking to connect with diversity advocates, community organisers, and companies committed to inclusive hiring.",
        "linkedin_url": "https://linkedin.com/in/varshakumari-ml",
    },
    {
        "id": "usr_088",
        "full_name": "Rahul Mathur",
        "email": "rahul.mathur@techwriting.ai",
        "phone": "+91-9889456789",
        "organization": "TechWrite AI",
        "role": "Technical Writer & AI Educator",
        "experience_level": "mid",
        "detailed_profile": "Making complex AI and ML topics understandable for developers and business leaders. Author of 3 books on Python and ML. Writing for Towards Data Science, MLMastery, and enterprise AI blogs. Built an LLM-powered documentation tool adopted by 5 tech companies. Interested in AI education, knowledge management, and technical communication.",
        "linkedin_url": "https://linkedin.com/in/rahulmathur-techwrite",
    },
    {
        "id": "usr_089",
        "full_name": "Aditi Nair",
        "email": "aditi.nair@open-source-ai.dev",
        "phone": "+91-9890567891",
        "organization": "Open Source AI Foundation",
        "role": "Open Source ML Engineer",
        "experience_level": "senior",
        "detailed_profile": "Core contributor to several open-source ML projects — contributed to Hugging Face Transformers, LlamaIndex, and ChromaDB. Believe strongly in open AI models as a counterweight to closed AI monopolies. Running a community of 8k open-source AI contributors in India. Interested in open models, AI infrastructure, and the politics of AI openness.",
        "linkedin_url": "https://linkedin.com/in/aditinair-oss",
    },
    {
        "id": "usr_090",
        "full_name": "Manjunath Hegde",
        "email": "manju.hegde@startup-studio.ai",
        "phone": "+91-9801789012",
        "organization": "AI Startup Studio",
        "role": "Startup Studio Director",
        "experience_level": "expert",
        "detailed_profile": "Running an AI-focused startup studio that has launched 8 AI companies in 3 years. Background in VC and product. Helping technical founders build GTM, pricing, and enterprise sales motions. Particularly interested in deep tech AI — robotics, drug discovery, and climate AI. Looking for technical co-founders, domain experts, and Series A investors.",
        "linkedin_url": "https://linkedin.com/in/manjunathhegde-studio",
    },

    # ── Data Scientists (91–96) ────────────────────────────────────────────────
    {
        "id": "usr_091",
        "full_name": "Supriya Pillai",
        "email": "supriya.pillai@ecommerce-ds.com",
        "phone": "+91-9812890123",
        "organization": "ShopAI",
        "role": "Senior Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Building recommender systems and search relevance for e-commerce — personalisation, query understanding, and A/B experimentation at scale. Previously at Meesho and Nykaa. Deep expertise in collaborative filtering, neural recommenders, and online learning. Interested in e-commerce AI, conversational commerce, and AI-driven personalisation.",
        "linkedin_url": "https://linkedin.com/in/supriyapillai-rec",
    },
    {
        "id": "usr_092",
        "full_name": "Hemant Sahu",
        "email": "hemant.sahu@manufacturing-ml.com",
        "phone": "+91-9823901234",
        "organization": "ManufactureAI",
        "role": "Industrial Data Scientist",
        "experience_level": "mid",
        "detailed_profile": "Applying ML to manufacturing — predictive maintenance, quality inspection, and production scheduling optimisation. Deployed anomaly detection on CNC machine sensor data at 8 factories reducing unplanned downtime by 40%. Familiar with SCADA systems, OPC-UA, and industrial IoT protocols. Interested in Industry 4.0, smart manufacturing, and AI for operational excellence.",
        "linkedin_url": "https://linkedin.com/in/hemantsahu-manuf",
    },
    {
        "id": "usr_093",
        "full_name": "Rohini Desai",
        "email": "rohini.desai@logistics-ml.io",
        "phone": "+91-9834012345",
        "organization": "LogisticsAI",
        "role": "Operations Research Scientist",
        "experience_level": "senior",
        "detailed_profile": "Solving logistics optimisation problems using ML and OR — last-mile delivery routing, warehouse slotting, and demand sensing. Built vehicle routing optimisation cutting delivery costs 20% for a D2C logistics company. Familiar with OR-Tools, Gurobi, and hybrid ML+OR approaches. Interested in autonomous logistics, drone delivery, and supply chain digitalisation.",
        "linkedin_url": "https://linkedin.com/in/rohinidesai-logistics",
    },
    {
        "id": "usr_094",
        "full_name": "Chaitanya Reddy",
        "email": "chaitanya.reddy@media-ai.com",
        "phone": "+91-9845123456",
        "organization": "MediaAI",
        "role": "Media & Entertainment Data Scientist",
        "experience_level": "mid",
        "detailed_profile": "Building content recommendation and viewer retention prediction models for a streaming platform. Personalisation engine serving 10M users. Background in social network analysis and ML. Interested in content AI, creator economy analytics, and predicting viral content. Currently exploring multimodal recommendation combining video, audio, and metadata signals.",
        "linkedin_url": "https://linkedin.com/in/chaitanyareddy-media",
    },
    {
        "id": "usr_095",
        "full_name": "Aishwarya Kumar",
        "email": "aishwarya.k@govtech-ai.in",
        "phone": "+91-9856234567",
        "organization": "GovTech India",
        "role": "Public Sector Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Using data and ML to improve government service delivery — predictive models for welfare beneficiary targeting, NLP for grievance categorisation, and geospatial analysis for infrastructure planning. Working with state governments on data-driven policy. Interested in digital public goods, open government data, and responsible AI in the public sector.",
        "linkedin_url": "https://linkedin.com/in/aishwaryakumar-gov",
    },
    {
        "id": "usr_096",
        "full_name": "Kiran Bose",
        "email": "kiran.bose@cybersecurity-ai.com",
        "phone": "+91-9867345678",
        "organization": "CyberAI",
        "role": "Cybersecurity Data Scientist",
        "experience_level": "senior",
        "detailed_profile": "Applying ML to cybersecurity — malware detection, intrusion detection systems, and threat intelligence. Trained graph neural networks on network traffic for APT detection. Familiar with MITRE ATT&CK framework and adversarial ML. Previously at CERT-In and a BFSI-focused security firm. Interested in AI-powered security operations, red-teaming, and AI model security.",
        "linkedin_url": "https://linkedin.com/in/kiranbose-cyber",
    },

    # ── Investors & VCs (97–100) ───────────────────────────────────────────────
    {
        "id": "usr_097",
        "full_name": "Vikrant Malhotra",
        "email": "vikrant.m@deeptech-vc.in",
        "phone": "+91-9878456789",
        "organization": "DeepTech Ventures",
        "role": "Principal, VC",
        "experience_level": "expert",
        "detailed_profile": "Investing in deep tech and AI startups at Series A — healthcare AI, climate tech, and AI infrastructure. Portfolio includes 4 unicorns. Background in electrical engineering and business. Looking for founders building defensible AI businesses with proprietary data or novel algorithms. Particularly excited about AI for Bharat and AI-enabled hardware.",
        "linkedin_url": "https://linkedin.com/in/vikrantmalhotra-vc",
    },
    {
        "id": "usr_098",
        "full_name": "Nalini Chandrasekaran",
        "email": "nalini.c@impact-fund.in",
        "phone": "+91-9889567890",
        "organization": "Impact AI Fund",
        "role": "Fund Manager",
        "experience_level": "expert",
        "detailed_profile": "Managing a Rs 200 Cr impact-focused AI fund investing in startups solving problems in healthcare, agriculture, education, and financial inclusion. Background in development finance and technology. Looking for mission-driven founders building AI products for underserved populations. Particularly interested in vernacular AI, rural tech, and AI for public systems.",
        "linkedin_url": "https://linkedin.com/in/nalinichandra-fund",
    },
    {
        "id": "usr_099",
        "full_name": "Tarun Kapoor",
        "email": "tarun.kapoor@corporate-innovation.com",
        "phone": "+91-9890678901",
        "organization": "Tata Innovation Cell",
        "role": "Corporate Innovation Director",
        "experience_level": "expert",
        "detailed_profile": "Leading AI adoption and open innovation at a large conglomerate — scouting AI startups for pilot partnerships, running internal AI capability building, and managing a corporate venture portfolio. Background in engineering and strategy consulting. Looking for AI startups ready for enterprise pilots, especially in manufacturing, logistics, and sustainability.",
        "linkedin_url": "https://linkedin.com/in/tarunkapoor-innovation",
    },
    {
        "id": "usr_100",
        "full_name": "Radha Krishnaswamy",
        "email": "radha.k@global-ai-fund.com",
        "phone": "+91-9801890123",
        "organization": "Global AI Partners",
        "role": "Venture Partner",
        "experience_level": "expert",
        "detailed_profile": "Venture partner at a global fund focused on India's AI ecosystem. Previously co-founded two AI companies (one NASDAQ-listed). Advising the government's National AI Mission. Connecting Indian AI talent with global markets and capital. Interested in AI research commercialisation, India-US AI bridges, and sovereign AI capacity building.",
        "linkedin_url": "https://linkedin.com/in/radhakrishnaswamy-gai",
    },
]


# ── Test queries ────────────────────────────────────────────────────────────────
TEST_QUERIES = [
    ("machine learning engineers",                              {}),
    ("healthcare AI and clinical NLP",                         {}),
    ("founders working in agriculture",                        {}),
    ("senior NLP researchers",                                 {"experience_level": "senior"}),
    ("climate change and sustainability",                      {}),
    ("deep learning computer vision",                          {}),
    ("fraud detection and fintech",                            {}),
    ("investor looking for deep tech startups",                {}),
    ("open source contributor AI tools",                       {}),
    ("drug discovery and computational biology",               {}),
    ("edge AI and embedded machine learning deployment",       {}),
    ("PhD student looking for research collaboration",         {}),
]


# ── Runner ────────────────────────────────────────────────────────────────────

def seed(base_url: str):
    print(f"\n{'─'*60}")
    print(f"  Seeding {len(ATTENDEES)} attendees → {base_url}/attendees/bulk")
    print(f"{'─'*60}")
    r = httpx.post(
        f"{base_url}/attendees/bulk",
        json=ATTENDEES,
        timeout=120,
    )
    r.raise_for_status()
    data = r.json()
    print(f"  ✓ {data['message']}")


def run_tests(base_url: str):
    print(f"\n{'─'*60}")
    print("  Running search tests")
    print(f"{'─'*60}\n")

    for query, filters in TEST_QUERIES:
        params = {"q": query, "limit": 5, **filters}
        r = httpx.get(f"{base_url}/search", params=params, timeout=30)
        r.raise_for_status()
        data = r.json()

        filter_str = f"  [filter: {filters}]" if filters else ""
        print(f"Query: \"{query}\"{filter_str}")

        if data.get("expanded_query"):
            print(f"  Groq expanded → \"{data['expanded_query'][:80]}…\"")

        print(f"  {data['total']} result(s):")
        for res in data["results"]:
            print(
                f"    [{res['score']:.3f}]  {res['full_name']:25s}  "
                f"{res['role']:35s}  {res['organization']}"
            )
        print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=BASE_URL)
    parser.add_argument("--test-only", action="store_true")
    args = parser.parse_args()

    if not args.test_only:
        seed(args.url)

    run_tests(args.url)
